(() => {
  "use strict";
  const F=window.EdusentiaFinanceRuntime;if(!F||window.EdusentiaFinancePortals)return;
  const {S,byId,esc,attr,money,date,statusLabel,statusClass,rpc,notify,dialog,printHtml,register,heading,schoolName}=F;

  function logoUrl(school={}){
    for(const image of [document.getElementById('brandLogo'),...document.querySelectorAll('[data-school-logo],.sidebar-brand img')]){
      const src=String(image?.currentSrc||image?.src||'').trim();
      if(src)return src;
    }
    const raw=String(school.logo_url||'').trim();
    if(/^https?:\/\//i.test(raw)||/^data:/i.test(raw)||/^blob:/i.test(raw))return raw;
    return '';
  }
  function schoolContactLines(school={}){
    return [school.address,school.phone,school.email,school.website].filter(Boolean);
  }
  function feeStatementBlock(s){
    if(!s)return '<div class="empty"><strong>No fee statement available</strong></div>';
    const accounts=s.accounts||[],payments=s.payments||[];
    return `<div class="finance-metrics compact"><div class="finance-metric"><span>Outstanding</span><strong>${money(s.outstanding)}</strong></div><div class="finance-metric"><span>Financial clearance</span><strong>${s.hold?.locked?'Restricted':'Clear'}</strong></div></div><div class="finance-table-scroll small"><table><thead><tr><th>Year</th><th>Term</th><th>Class</th><th>Term Fee</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${accounts.map(a=>`<tr><td>${esc(a.academic_year_name)}</td><td>${esc(a.term_name)}</td><td>${esc(a.class_name)}</td><td>${money(a.term_fee)}</td><td>${money(a.paid)}</td><td>${money(a.balance)}</td><td><span class="status ${statusClass(a.status)}">${esc(statusLabel(a.status))}</span></td></tr>`).join('')||'<tr><td colspan="7">No fee obligations</td></tr>'}</tbody></table></div><h4>Payments</h4><div class="finance-table-scroll small"><table><thead><tr><th>Receipt</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${esc(p.receipt_no||'—')}</td><td>${esc(date(p.transaction_date))}</td><td>${money(p.amount)}</td><td>${esc(statusLabel(p.method))}</td><td>${esc(p.reference||'—')}</td><td>${p.reversed?'Reversed':'Posted'}</td></tr>`).join('')||'<tr><td colspan="6">No payments</td></tr>'}</tbody></table></div>`;
  }

  function printFee(s){
    if(!s){notify('Statement unavailable','No fee statement data is available to print.','warning');return}
    const student=s.student||{},school=s.school||{},accounts=s.accounts||[],payments=s.payments||[];
    const latest=accounts.length?accounts[accounts.length-1]:{};
    const generated=new Date().toLocaleString('en-GH',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
    const clearance=s.hold?.locked?'Restricted':'Clear';
    const clearanceClass=s.hold?.locked?'restricted':'clear';
    const logo=logoUrl(school),contacts=schoolContactLines(school);
    const accountRows=accounts.map(a=>`<tr><td>${esc(a.academic_year_name||'—')}</td><td>${esc(a.term_name||'—')}</td><td>${esc(a.class_name||'—')}</td><td class="num">${esc(money(a.term_fee))}</td><td class="num">${esc(money(a.paid))}</td><td class="num strong">${esc(money(a.balance))}</td><td><span class="fee-print-status ${esc(String(a.status||''))}">${esc(statusLabel(a.status)||'—')}</span></td></tr>`).join('')||'<tr><td colspan="7" class="empty-cell">No fee obligations recorded.</td></tr>';
    const paymentRows=payments.map(p=>`<tr><td>${esc(p.receipt_no||'—')}</td><td>${esc(date(p.transaction_date))}</td><td class="num">${esc(money(p.amount))}</td><td>${esc(statusLabel(p.method)||'—')}</td><td>${esc(p.reference||'—')}</td><td><span class="fee-print-status ${p.reversed?'reversed':'posted'}">${p.reversed?'Reversed':'Posted'}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty-cell">No payments have been recorded for this student.</td></tr>';
    const holdReason=s.hold?.locked&&s.hold?.reason?`<div class="fee-print-notice"><strong>Financial restriction</strong><span>${esc(s.hold.reason)}</span></div>`:'';
    const body=`
      <style>
        @page{size:A4 portrait;margin:12mm}
        *{box-sizing:border-box}body{padding:0!important;margin:0!important;color:#10233f!important;background:#fff!important;font-family:Arial,Helvetica,sans-serif!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}
        .fee-print-sheet{max-width:190mm;margin:0 auto;font-size:11px;line-height:1.4;color:#10233f}.fee-print-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;padding:0 0 13px;border-bottom:3px solid #0b4da3}.fee-print-brand{display:flex;align-items:flex-start;gap:12px;min-width:0}.fee-print-brand img{width:58px;height:58px;object-fit:contain}.fee-print-brand h1{font-size:21px;line-height:1.15;margin:0 0 3px;color:#082f6b}.fee-print-brand .motto{font-size:9px;font-weight:700;color:#53677f;margin-bottom:3px}.fee-print-brand .contact{font-size:8px;line-height:1.4;color:#6a7a8e}.fee-print-brand .contact span{display:block}.fee-print-document{text-align:right;min-width:155px}.fee-print-document strong{display:block;font-size:17px}.fee-print-document span{display:block;color:#69798d;margin-top:4px;font-size:9px}
        .fee-print-student{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:15px 0 12px}.fee-print-field{border:1px solid #d9e2ef;border-radius:8px;padding:9px 10px;background:#f8faff}.fee-print-field span{display:block;color:#68788c;font-size:9px;text-transform:uppercase;letter-spacing:.4px;font-weight:700;margin-bottom:3px}.fee-print-field strong{display:block;font-size:11px;overflow-wrap:anywhere}.fee-print-summary{display:grid;grid-template-columns:1.35fr 1fr 1fr;gap:10px;margin-bottom:16px}.fee-print-card{border:1px solid #d6e0ed;border-radius:10px;padding:12px}.fee-print-card span{display:block;color:#66778c;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.45px;margin-bottom:4px}.fee-print-card strong{display:block;font-size:18px;color:#0b3269}.fee-print-card.clear strong{color:#14724d}.fee-print-card.restricted strong{color:#a1353d}.fee-print-notice{display:flex;gap:8px;border:1px solid #efc9cc;background:#fff5f5;border-radius:8px;padding:10px 11px;margin:0 0 14px;color:#7d2630}.fee-print-notice strong{white-space:nowrap}
        .fee-print-section{margin-top:16px}.fee-print-section-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:7px}.fee-print-section-head h2{font-size:13px;margin:0}.fee-print-section-head span{font-size:9px;color:#738196}.fee-print-sheet table{width:100%;border-collapse:separate!important;border-spacing:0;margin:0!important;border:1px solid #d8e1ed;border-radius:8px;overflow:hidden}.fee-print-sheet th{background:#eef4fb!important;color:#344a66!important;font-size:8.5px!important;text-transform:uppercase;letter-spacing:.35px;font-weight:800;padding:8px 7px!important;border:0!important;border-bottom:1px solid #d8e1ed!important;white-space:nowrap}.fee-print-sheet td{padding:8px 7px!important;border:0!important;border-bottom:1px solid #e6ebf2!important;font-size:9.5px!important}.fee-print-sheet tbody tr:last-child td{border-bottom:0!important}.fee-print-sheet .num{text-align:right;white-space:nowrap}.fee-print-sheet .strong{font-weight:800;color:#0a326b}.fee-print-sheet .empty-cell{text-align:center;color:#718096;padding:15px!important}.fee-print-status{display:inline-flex;align-items:center;min-height:21px;padding:0 7px;border-radius:999px;background:#edf2f7;color:#475569;font-size:8px;font-weight:800;white-space:nowrap;text-transform:capitalize}.fee-print-status.fully_paid,.fee-print-status.paid,.fee-print-status.posted{background:#e4f6ed;color:#176b49}.fee-print-status.partial_paid{background:#fff3d8;color:#805c0c}.fee-print-status.unpaid,.fee-print-status.reversed{background:#fde8ea;color:#9a3039}.fee-print-footer{display:flex;justify-content:space-between;gap:16px;border-top:1px solid #dbe3ee;margin-top:20px;padding-top:10px;color:#748398;font-size:8.5px}.fee-print-footer strong{color:#52657d}
        @media print{.fee-print-sheet{max-width:none}.fee-print-section,.fee-print-card,.fee-print-field,table,tr{break-inside:avoid;page-break-inside:avoid}}
      </style>
      <article class="fee-print-sheet">
        <header class="fee-print-head"><div class="fee-print-brand">${logo?`<img src="${attr(logo)}" alt="School logo">`:''}<div><h1>${esc(school.school_name||schoolName())}</h1>${school.motto?`<div class="motto">${esc(school.motto)}</div>`:''}<div class="contact">${contacts.map(v=>`<span>${esc(v)}</span>`).join('')}</div></div></div><div class="fee-print-document"><strong>Student Fee Statement</strong><span>Generated ${esc(generated)}</span></div></header>
        <section class="fee-print-student"><div class="fee-print-field"><span>Student</span><strong>${esc(student.full_name||'—')}</strong></div><div class="fee-print-field"><span>Admission No.</span><strong>${esc(student.admission_no||'—')}</strong></div><div class="fee-print-field"><span>Class</span><strong>${esc(latest.class_name||'—')}</strong></div><div class="fee-print-field"><span>Academic Period</span><strong>${esc([latest.academic_year_name,latest.term_name].filter(Boolean).join(' • ')||'—')}</strong></div></section>
        <section class="fee-print-summary"><div class="fee-print-card"><span>Total outstanding</span><strong>${esc(money(s.outstanding))}</strong></div><div class="fee-print-card ${clearanceClass}"><span>Financial clearance</span><strong>${esc(clearance)}</strong></div><div class="fee-print-card"><span>Payments recorded</span><strong>${esc(String(payments.filter(p=>!p.reversed).length))}</strong></div></section>${holdReason}
        <section class="fee-print-section"><div class="fee-print-section-head"><h2>Fee Obligations and Balances</h2><span>Live school finance ledger</span></div><table><thead><tr><th>Year</th><th>Term</th><th>Class</th><th>Term Fee</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${accountRows}</tbody></table></section>
        <section class="fee-print-section"><div class="fee-print-section-head"><h2>Payment History</h2><span>Posted and reversed transactions</span></div><table><thead><tr><th>Receipt</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th></tr></thead><tbody>${paymentRows}</tbody></table></section>
        <footer class="fee-print-footer"><span>${esc(school.report_footer||'This is a computer-generated statement from Edusentia Enterprise.')}</span><span><strong>${esc(school.school_name||schoolName())}</strong></span></footer>
      </article>`;
    printHtml(`Fee Statement - ${student.full_name||'Student'}`,body);
  }

  function printFeeSummary(s){
    if(!s){notify('Summary unavailable','No fee statement data is available to print.','warning');return}
    const student=s.student||{},school=s.school||{},accounts=s.accounts||[];
    const latest=accounts.length?accounts[accounts.length-1]:{};
    const logo=logoUrl(school),contacts=schoolContactLines(school),clearance=s.hold?.locked?'Restricted':'Clear';
    const generated=new Date().toLocaleString('en-GH',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
    const body=`<style>
      @page{size:A6 portrait;margin:5mm}*{box-sizing:border-box}html,body{margin:0!important;padding:0!important;background:#fff!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.fee-slip{width:95mm;min-height:138mm;margin:0 auto;border:1px solid #d3dce8;font-family:Arial,Helvetica,sans-serif;color:#13253e;position:relative;overflow:hidden}.fee-slip-top{height:3mm;background:#0b4da3}.fee-slip-head{display:grid;grid-template-columns:15mm 1fr;gap:3mm;padding:4mm;border-bottom:1px solid #d7e0eb}.fee-slip-head img{width:13mm;height:13mm;object-fit:contain}.fee-slip-head h1{font-size:10.5pt;margin:0;color:#082f6b;line-height:1.05}.fee-slip-head .motto{font-size:5pt;font-weight:700;color:#5e7188;margin-top:.8mm}.fee-slip-head .contact{font-size:4.5pt;color:#718096;line-height:1.3;margin-top:1mm}.fee-slip-head .contact span{display:block}.fee-slip-title{padding:2.4mm 4mm;background:#f5f8fc;border-bottom:1px solid #d7e0eb;font-weight:800;font-size:8pt;color:#0b3b7c}.fee-slip-body{padding:3mm 4mm}.fee-slip-grid{display:grid;grid-template-columns:1fr 1fr;gap:2mm 3mm}.fee-slip-field{border-bottom:1px dotted #cbd5e1;padding-bottom:1.5mm}.fee-slip-field span{display:block;font-size:4.6pt;text-transform:uppercase;color:#738196;font-weight:700}.fee-slip-field strong{display:block;font-size:6.4pt;margin-top:.5mm}.fee-slip-balance{margin:4mm 0 3mm;background:#0b4da3;color:#fff;border-radius:2mm;padding:4mm;text-align:center}.fee-slip-balance span{display:block;font-size:5pt;text-transform:uppercase;letter-spacing:.4px}.fee-slip-balance strong{display:block;font-size:18pt;margin:1mm 0}.fee-slip-status{display:grid;grid-template-columns:1fr 1fr;gap:2mm}.fee-slip-card{border:1px solid #d7e0eb;border-radius:2mm;padding:2.5mm}.fee-slip-card span{display:block;font-size:4.6pt;text-transform:uppercase;color:#708095;font-weight:700}.fee-slip-card strong{display:block;font-size:8pt;margin-top:.8mm}.fee-slip-card.clear strong{color:#14724d}.fee-slip-card.restricted strong{color:#a1353d}.fee-slip-note{font-size:5pt;line-height:1.45;color:#62748b;margin-top:3mm;padding:2.5mm;background:#f8fafc;border-radius:2mm}.fee-slip-footer{position:absolute;left:0;right:0;bottom:0;padding:2mm 4mm;border-top:1px solid #d7e0eb;background:#f5f8fc;font-size:4.2pt;color:#758398;text-align:center}@media print{html,body{width:105mm!important;height:148mm!important;overflow:hidden!important}}
    </style><article class="fee-slip"><div class="fee-slip-top"></div><header class="fee-slip-head">${logo?`<img src="${attr(logo)}" alt="School logo">`:''}<div><h1>${esc(school.school_name||schoolName())}</h1>${school.motto?`<div class="motto">${esc(school.motto)}</div>`:''}<div class="contact">${contacts.map(v=>`<span>${esc(v)}</span>`).join('')}</div></div></header><div class="fee-slip-title">A6 FEE BALANCE SUMMARY</div><main class="fee-slip-body"><div class="fee-slip-grid"><div class="fee-slip-field"><span>Student</span><strong>${esc(student.full_name||'—')}</strong></div><div class="fee-slip-field"><span>Admission No.</span><strong>${esc(student.admission_no||'—')}</strong></div><div class="fee-slip-field"><span>Class</span><strong>${esc(latest.class_name||'—')}</strong></div><div class="fee-slip-field"><span>Academic Period</span><strong>${esc([latest.academic_year_name,latest.term_name].filter(Boolean).join(' • ')||'—')}</strong></div></div><div class="fee-slip-balance"><span>Outstanding balance</span><strong>${esc(money(s.outstanding))}</strong></div><div class="fee-slip-status"><div class="fee-slip-card ${s.hold?.locked?'restricted':'clear'}"><span>Financial clearance</span><strong>${esc(clearance)}</strong></div><div class="fee-slip-card"><span>Current term fee</span><strong>${esc(money(latest.term_fee||0))}</strong></div><div class="fee-slip-card"><span>Paid</span><strong>${esc(money(latest.paid||0))}</strong></div><div class="fee-slip-card"><span>Term balance</span><strong>${esc(money(latest.balance||0))}</strong></div></div><div class="fee-slip-note">This summary shows the current finance ledger position. For complete fee obligations and payment history, use the full Student Fee Statement.</div></main><footer class="fee-slip-footer">Generated ${esc(generated)} • ${esc(school.tenant_code||'')} • Edusentia Enterprise</footer></article>`;
    printHtml(`Fee Summary - ${student.full_name||'Student'}`,body);
  }

  async function renderParent(){
    heading('Fees','Linked student fee obligations, balances and payment history');
    const data=await rpc('finance_my_children_fees'),children=data.children||[];
    byId('content').innerHTML=`<div class="finance-workspace"><div class="page-head"><div><h3>My Children - Fees</h3><p>Read-only live fee information from the school finance ledger</p></div></div><div class="grid ${children.length>1?'two':''}">${children.length?children.map(c=>`<section class="panel"><div class="panel-header"><div><h3>${esc(c.full_name)}</h3><p>${esc(c.admission_no)} • ${esc(c.class_name||'')}</p></div><div class="button-row"><button class="button secondary small" data-parent-print="${attr(c.id)}">Full statement</button><button class="button ghost small" data-parent-summary="${attr(c.id)}">A6 summary</button></div></div><div class="panel-body">${c.statement?.hold?.locked?`<div class="finance-hold-banner"><strong>Financial clearance restriction</strong><span>${esc(c.statement.hold.reason||'Contact the school Accounts Office for clearance.')}</span></div>`:''}${feeStatementBlock(c.statement)}</div></section>`).join(''):'<section class="panel pad"><div class="empty"><strong>No linked student fee records</strong></div></section>'}</div></div>`;
    byId('content').querySelectorAll('[data-parent-print]').forEach(b=>b.onclick=()=>{const c=children.find(x=>x.id===b.dataset.parentPrint);if(c)printFee(c.statement)});
    byId('content').querySelectorAll('[data-parent-summary]').forEach(b=>b.onclick=()=>{const c=children.find(x=>x.id===b.dataset.parentSummary);if(c)printFeeSummary(c.statement)});
  }

  async function renderStudent(){
    heading('My Academics & Fees','Published academic results and live fee information');
    const d=await rpc('get_my_student_portal');
    if(!d.linked){byId('content').innerHTML='<section class="panel pad"><strong>No linked student record</strong><p>Ask the System Administrator to link this portal account to your Student Management record.</p></section>';return}
    const s=d.student,fees=d.fee_statement,reports=d.reports||[];
    byId('content').innerHTML=`<div class="finance-workspace"><div class="page-head"><div><h3>${esc(s.full_name)}</h3><p>${esc(s.admission_no)} • ${esc(s.class_name||'')}</p></div></div>${d.financial_hold?.locked?`<div class="finance-hold-banner"><strong>Financial clearance restriction active</strong><span>${esc(d.financial_hold.reason||'Contact the Accounts Office for clearance.')}</span></div>`:''}<section class="panel"><div class="panel-header"><div><h3>Fee Payments & Statement</h3><p>Read-only live financial record</p></div><div class="button-row"><button class="button secondary" id="studentFeePrint">Full statement</button><button class="button ghost" id="studentFeeSummary">A6 summary</button></div></div><div class="panel-body">${feeStatementBlock(fees)}</div></section><section class="panel"><div class="panel-header"><div><h3>Published Academic Results</h3><p>Published results remain school records; financial policy may restrict viewing only.</p></div></div><div class="finance-table-scroll"><table><thead><tr><th>Academic Year</th><th>Term</th><th>Report</th><th>Average</th><th>Status</th><th></th></tr></thead><tbody>${reports.length?reports.map(r=>`<tr><td>${esc(r.academic_year_name)}</td><td>${esc(r.term_name)}</td><td>${esc(r.report_number||'—')}</td><td>${r.locked?'—':`${Number(r.average||0).toFixed(1)}%`}</td><td><span class="status ${r.locked?'withdrawn':'published'}">${r.locked?'Locked':'Published'}</span></td><td><button class="button ${r.locked?'ghost':'primary'} small" data-result-view="${attr(r.id)}">${r.locked?'View status':'View grades'}</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty"><strong>No published academic results</strong></div></td></tr>'}</tbody></table></div></section></div>`;
    byId('studentFeePrint').onclick=()=>printFee(fees);byId('studentFeeSummary').onclick=()=>printFeeSummary(fees);
    byId('content').querySelectorAll('[data-result-view]').forEach(b=>b.onclick=()=>openResult(b.dataset.resultView));
  }

  async function openResult(reportId){
    try{
      const d=await rpc('finance_portal_report_detail',{target_report_id:reportId}),q=dialog('Published Academic Result','Read-only published academic record');
      if(d.locked){byId('financeDialogBody').innerHTML=`<div class="finance-hold-banner"><strong>Grades are currently restricted</strong><span>${esc(d.hold?.reason||'Contact the Accounts Office for financial clearance.')}</span></div><div class="button-row"><button class="button ghost" id="resultClose">Close</button></div>`}
      else{const r=d.report||{},subs=d.subjects||[];byId('financeDialogBody').innerHTML=`<div class="finance-statement-head"><h3>${esc(r.student||'Student')}</h3><span>${esc(r.academic_year_name)} • ${esc(r.term_name)} • ${esc(r.class_name)}</span></div><div class="finance-metrics compact"><div class="finance-metric"><span>Average</span><strong>${Number(d.average||0).toFixed(1)}%</strong></div><div class="finance-metric"><span>Position</span><strong>${esc(r.position??'—')}</strong></div></div><div class="finance-table-scroll"><table><thead><tr><th>Subject</th><th>Total</th><th>Grade</th><th>Remark</th></tr></thead><tbody>${subs.map(x=>`<tr><td>${esc(x.subject)}</td><td>${Number(x.total_score||0).toFixed(1)}</td><td>${esc(x.grade||'')}</td><td>${esc(x.remark||'')}</td></tr>`).join('')||'<tr><td colspan="4">No subject results</td></tr>'}</tbody></table></div><div class="finance-comments"><div><strong>Teacher comment</strong><span>${esc(r.teacher_comment||'—')}</span></div><div><strong>Principal comment</strong><span>${esc(r.head_comment||'—')}</span></div></div><div class="button-row"><button class="button primary" id="resultPrint">Print result</button><button class="button ghost" id="resultClose">Close</button></div>`;byId('resultPrint').onclick=()=>printHtml(`Academic Result - ${r.student||''}`,`<h2>${esc(schoolName())}</h2><h3>Published Academic Result</h3><p><strong>${esc(r.student)}</strong><br>${esc(r.admission_no)} • ${esc(r.class_name)} • ${esc(r.academic_year_name)} / ${esc(r.term_name)}</p><table><thead><tr><th>Subject</th><th>Total</th><th>Grade</th><th>Remark</th></tr></thead><tbody>${subs.map(x=>`<tr><td>${esc(x.subject)}</td><td>${Number(x.total_score||0).toFixed(1)}</td><td>${esc(x.grade||'')}</td><td>${esc(x.remark||'')}</td></tr>`).join('')}</tbody></table><p><strong>Average:</strong> ${Number(d.average||0).toFixed(1)}%</p>`)}
      byId('resultClose').onclick=()=>q.close();q.showModal();
    }catch(e){notify('Result could not be opened',F.friendly(e),'error')}
  }

  window.EdusentiaFinancePortals={renderParent,renderStudent,printFee,printFeeSummary};
  register('parent_guardian',renderParent);register('student',renderStudent);
})();