// Platform System Administrator dedicated sign-in and mobile console refresh.
const CACHE = "edusentia-neon-v27";
const SHELL = ["./","./index.html","./about.html","./support.html","./privacy.html","./terms.html","./info-pages.css","./config.js","./api-client.js","./app.js","./parity-common.js","./parity-academics.js","./parity-students.js","./parity-teachers.js","./parity-principal.js","./parity-timetable.js","./parity-reports.js","./parity-audit-security-finance.js","./parity-operations.js","./parity-enterprise-workspaces.js","./tenant-class-teacher-workspace-parity-v1.js","./style.css","./r37-final-ui.css","./neon-edition.css","./manifest.webmanifest","./assets/edusentia-mark.svg","./assets/school-logo.png","./assets/vendor/jszip-3.10.1.min.js","./tenant-r40-product-fixes.js","./tenant-r40-v9-list-resilience.js","./tenant-accountant-parent-follow-up-v1.js","./tenant-accountant-parent-follow-up-v2.js","./tenant-user-credential-actions-v2.js","./tenant-user-credential-actions-v3.js","./tenant-backup-r2-download-v1.js","./tenant-backup-r2-download-core-r42-v18.js","./tenant-teacher-subject-summary.js","./tenant-teacher-subject-summary-v2.js","./platform-admin.html","./platform-saas-admin.html","./platform-api-client.js","./platform-admin.js","./platform-saas-admin.js","./platform-saas-admin.css","./platform-r40-mobile.css","./workspace-canvas.css","./r40-v9.css","./platform-r40-v9-mfa-resilience.css","./platform-r40-v9-list-resilience.css","./assets/vendor/qrcode-1.0.0.min.js","./register.html","./register.js","./admin-setup.html","./admin-setup.js","./neon-supabase-compat.js","./finance-enterprise.css","./finance-core.js","./finance-payroll.js","./finance-accounts.js","./finance-professional-receipts.js","./finance-portals.js","./finance-invoices-v1.js","./tenant-accountant-dashboard-v1.js","./tenant-accountant-student-roles-v2.js","./tenant-accountant-student-submit-v3.js","./tenant-hr-staff-v1.js","./tenant-student-services-v1.js","./tenant-student-services-actions-v1.js","./tenant-student-portal-v1.js","./tenant-student-portal-v2.js","./tenant-student-portal-v2-refinements.js","./tenant-institution-academics-loader-v1.js","./tenant-institution-academics-v1.js"];
self.addEventListener("install", e => e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())));
self.addEventListener("activate", e => e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin || e.request.method !== "GET") return;
  e.respondWith(fetch(e.request).then(r => { const copy=r.clone(); caches.open(CACHE).then(c => c.put(e.request,copy)); return r; }).catch(() => caches.match(e.request).then(r => r || caches.match("./index.html"))));
});
