import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8");
test("r42-v18 accounts staff deletion invariant is preserved",()=>{const sql=read("database/migrations/0005_finance_hr_admissions.sql");assert.match(sql,/archive-only/);assert.doesNotMatch(sql,/delete from finance\.accounts_office_staff/i)});
test("frontend never receives database configuration",()=>{const c=read("frontend/config.js");assert.doesNotMatch(c,/DATABASE_URL|postgresql:\/\//i)});
test("session cookie is HttpOnly and Secure",()=>{const a=read("worker/src/auth.ts");assert.match(a,/HttpOnly/);assert.match(a,/Secure/)});
test("RLS migration forces tenant policies",()=>{const s=read("database/migrations/0007_rls_and_runtime_grants.sql");assert.match(s,/force row level security/i);assert.match(s,/tenant_isolation/)});

test("CLI bootstrap is secret-gated without weakening normal origin checks",()=>{const i=read("worker/src/index.ts");assert.match(i,/bootstrapCli/);assert.match(i,/x-bootstrap-secret/);assert.match(i,/origin!==env\.APP_ORIGIN/)});
test("retired modules remain retired",()=>{const m=read("docs/MODULE_CATALOG.md");for(const x of ["Inventory","Library","Transport"])assert.match(m,new RegExp(`- ${x}`))});
test("platform license catalog is outside tenant runtime write-default schema",()=>{const m=read("database/migrations/0013_operations_compliance.sql");assert.match(m,/platform\.license_plans/);assert.match(m,/grant select on platform\.license_plans,platform\.license_feature_catalog/);assert.doesNotMatch(m,/grant select,insert,update,delete on all tables in schema platform/)});

test("Turnstile is enforced on login in both browser and Worker",()=>{const c=read("frontend/config.js"),a=read("frontend/api-client.js"),r=read("worker/src/routes.ts"),v=read("worker/src/turnstile.ts");assert.match(c,/turnstileSiteKey:\s*"0x/);assert.match(a,/turnstileToken/);assert.match(r,/verifyTurnstile/);assert.match(v,/siteverify/);assert.match(v,/result\.action\s*!==\s*expectedAction/);assert.match(v,/hostname/)});

test("MFA-required users must complete a second factor before session issuance",()=>{const a=read("worker/src/auth.ts"),m=read("worker/src/mfa.ts"),s=read("database/migrations/0016_mfa_login_challenges.sql");assert.match(a,/if\(!row\.mfa_required\)/);assert.match(a,/mfaRequired:true/);assert.match(a,/assuranceLevel:2/);assert.match(a,/m\.mfa_required or s\.assurance_level>=2/);assert.match(m,/AES-GCM/);assert.match(m,/SHA-1/);assert.match(s,/authn\.login_challenges/);assert.match(s,/mfa_recovery_codes/)});

test("Platform Super Administrator is distinct from tenant system_admin",()=>{const s=read("database/migrations/0017_platform_control_plane_foundation.sql"),f=read("database/migrations/0018_platform_super_admin_functions.sql"),a=read("worker/src/platform-auth.ts"),r=read("worker/src/platform-routes.ts");assert.match(s,/platform\.admins/);assert.match(s,/platform_super_admin/);assert.match(f,/bootstrap_first_super_admin/);assert.match(f,/approve_registration/);assert.match(a,/platform-session:v1/);assert.match(a,/assurance_level>=2/);assert.match(r,/platform_login/);assert.doesNotMatch(a,/tenant_memberships/)});
test("Platform onboarding keeps registration approval and licensing behind AAL2 platform routes",()=>{const r=read("worker/src/platform-routes.ts"),f=read("database/migrations/0018_platform_super_admin_functions.sql");assert.match(r,/Platform Super Administrator session is required/);assert.match(r,/configure_initial_license/);assert.match(r,/approve_registration/);assert.match(r,/issue_plan_authorization/);assert.match(r,/platform_capacity_snapshot/);assert.match(f,/mfa_required/);});

test("Tenant administrator setup links are single-use and never expose password tables",()=>{const m=read("database/migrations/0019_tenant_admin_setup_handoff.sql"),r=read("worker/src/platform-routes.ts"),g=read("database/runtime-role.sql"),u=read("frontend/admin-setup.js");assert.match(m,/tenant_admin_setup_tokens/);assert.match(m,/used_at is null/);assert.match(m,/set used_at=now/);assert.match(m,/complete_admin_setup/);assert.match(r,/tenant-admin-setup:v2/);assert.match(r,/randomToken\(32\)/);assert.match(r,/passwordHash\(password\)/);assert.match(g,/revoke all on platform\.tenant_admin_setup_tokens/);assert.match(g,/revoke all on authn\.password_credentials/);assert.doesNotMatch(u,/DATABASE_URL|postgresql:\/\//i)});
test("Capacity override reason is persisted in schema 0019",()=>{const m=read("database/migrations/0019_tenant_admin_setup_handoff.sql");assert.match(m,/student_capacity_reason text not null default/);});

test("Isolated Neon tenant provisioning uses a separate least-privilege creator",()=>{const p=read("database/provisioner-role.sql"),w=read(".github/workflows/deploy-worker.yml"),x=read("worker/src/provisioning.ts");assert.match(p,/createdb nocreaterole noinherit nobypassrls/i);assert.match(p,/nosuperuser/i);assert.match(w,/PROVISIONER_DATABASE_URL/);assert.match(w,/tenant-template\/install\.sh/);assert.match(x,/create database/);assert.match(x,/template/);assert.match(x,/revoke connect on database/);assert.match(x,/edusentia_worker_runtime/);});
test("Tenant template owns school auth and operational data",()=>{const t=read("database/tenant-template/0020_tenant_runtime_parity.sql");assert.match(t,/app\.platform_initialize_tenant/);assert.match(t,/authn\.platform_set_initial_password_by_email/);assert.match(t,/authn\.platform_reset_mfa_by_email/);assert.match(t,/app\.platform_health_snapshot/);assert.match(t,/mfa_required.*true/s);});
test("School sessions route to isolated databases rather than the master",()=>{const a=read("worker/src/auth.ts"),r=read("worker/src/routes.ts"),d=read("worker/src/tenant-db.ts");assert.match(a,/platform\.resolve_login_route/);assert.match(a,/tenantDb\(env/);assert.match(a,/routedToken/);assert.match(r,/tenantDb\(env,ctx\.databaseName\)/);assert.match(d,/databaseUrl/);assert.match(d,/tokenTenantCode/);});
test("Tenant template is locked between provisioning operations",()=>{const s=read("database/tenant-template/install.sh");assert.match(s,/allow_connections false/i);assert.match(s,/revoke connect on database/);assert.match(s,/grant connect on database.*edusentia_provisioner/i);});

test("Tenant template installs certified core and least-privilege Worker grants",()=>{const i=read("database/tenant-template/install.sh"),g=read("database/tenant-template/runtime-role.sql"),r=read("database/reference-compat/install-core.sh");assert.match(i,/reference-compat\/install-core\.sh/);assert.match(i,/tenant-template\/runtime-role\.sql/);assert.match(i,/0027/);assert.match(g,/revoke all on authn\.password_credentials from edusentia_worker_runtime/i);assert.match(g,/grant select on authn\.users to edusentia_worker_runtime/i);assert.match(g,/authn\.lookup_login\(text,text\)/);assert.match(r,/0027_reference_core_part_01/);});
test("Tenant release health requires runtime and certified compatibility identities",()=>{const x=read("worker/src/tenant-release.ts"),p=read("worker/src/provisioning.ts"),r=read("worker/src/platform-routes.ts");assert.match(x,/TENANT_RUNTIME_SCHEMA_VERSION="0020"/);assert.match(x,/CERTIFIED_COMPAT_SCHEMA_VERSION="0027"/);assert.match(x,/get_bootstrap_data/);assert.match(p,/inspectTenantRelease/);assert.match(p,/tenant_release_invalid/);assert.match(r,/certifiedCoreReady/);});
test("Production school onboarding is limited to Basic JHS and Senior High",()=>{const r=read("worker/src/platform-routes.ts"),h=read("frontend/register.html"),m=read("docs/MODULE_CATALOG.md");assert.match(r,/new Set\(\["basic_jhs","senior_high"\]\)/);assert.doesNotMatch(h,/combined_pretertiary|tertiary/);assert.match(m,/Basic\/JHS and Senior High School/);});

test("Certified RPC bridge uses a fixed server-side allowlist and trusted tenant context",()=>{const b=read("worker/src/certified-rpc.ts"),r=read("worker/src/routes.ts"),g=read("database/tenant-template/runtime-role.sql"),a=read("frontend/api-client.js");assert.match(b,/CERTIFIED_RPC_OPERATIONS/);assert.match(b,/get_bootstrap_data/);assert.match(b,/search_students/);assert.match(b,/save_student/);assert.match(b,/transition_report_status/);assert.match(b,/list_notifications/);assert.match(b,/certified_rpc_not_allowed/);assert.match(b,/tenantTx/);assert.doesNotMatch(b,/select\s+public\.\$\{/i);assert.match(r,/invokeCertifiedRpc\(sql,ctx/);assert.match(g,/public\.get_bootstrap_data\(\)/);assert.match(a,/certifiedRpc/);});
