begin;
create table if not exists finance.accounts_office_staff(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,staff_no text not null,full_name text not null,email text,phone text,contact_address text not null default '',job_title text not null default 'Accounts Officer',profile_user_id uuid references authn.users(id),active boolean not null default true,archived_at timestamptz,created_by uuid references authn.users(id),created_at timestamptz not null default now(),unique(tenant_id,staff_no));
create table if not exists finance.fee_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,code text not null,name text not null,amount numeric(14,2) not null check(amount>=0),active boolean not null default true,unique(tenant_id,code));
create table if not exists finance.invoices(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,invoice_no text not null,student_id uuid not null references app.students(id),term_id uuid references academics.terms(id),amount_due numeric(14,2) not null default 0,amount_paid numeric(14,2) not null default 0,status text not null default 'open' check(status in('open','part_paid','paid','overdue','void')),due_date date,created_at timestamptz not null default now(),created_by uuid references authn.users(id),unique(tenant_id,invoice_no));
create table if not exists finance.payments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,receipt_no text not null,student_id uuid not null references app.students(id),invoice_id uuid references finance.invoices(id),amount numeric(14,2) not null check(amount>0),method text not null default 'cash',reference text,received_by uuid references authn.users(id),received_at timestamptz not null default now(),reversed_at timestamptz,reversal_reason text,unique(tenant_id,receipt_no));
create table if not exists finance.payroll_runs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,period_start date not null,period_end date not null,status text not null default 'draft',created_by uuid references authn.users(id),created_at timestamptz not null default now());
create table if not exists finance.payroll_entries(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,payroll_run_id uuid not null references finance.payroll_runs(id) on delete cascade,staff_id uuid not null references app.staff(id),gross_amount numeric(14,2) not null default 0,deductions numeric(14,2) not null default 0,net_amount numeric(14,2) generated always as (gross_amount-deductions) stored,paid_at timestamptz,unique(payroll_run_id,staff_id));
create table if not exists app.admissions_applications(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,application_no text not null,first_name text not null,middle_name text,last_name text not null,gender text,date_of_birth date,guardian_name text not null,guardian_phone text,guardian_email text,address text,previous_school text,applying_class_id uuid references academics.classes(id),target_academic_year_id uuid references academics.academic_years(id),status text not null default 'draft',student_id uuid references app.students(id),submitted_at timestamptz,decided_at timestamptz,created_by uuid references authn.users(id),created_at timestamptz not null default now(),unique(tenant_id,application_no));
create table if not exists app.hr_staff_profiles(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,staff_id uuid not null references app.staff(id),employment_status text not null default 'active',hire_date date,department text,emergency_contact jsonb not null default '{}'::jsonb,metadata jsonb not null default '{}'::jsonb,unique(tenant_id,staff_id));
-- r42-v18 invariant: Accounts Office identities are archive-only; no permanent-delete function is provided.
insert into app.schema_migrations(version) values ('0005_finance_hr_admissions') on conflict do nothing;
commit;
