begin;
create schema if not exists services;
create schema if not exists documents;
create schema if not exists ops;

do $$begin if exists(select 1 from pg_roles where rolname='edusentia_runtime') then
  grant usage on schema services,documents,ops to edusentia_runtime;
  alter default privileges in schema services grant select,insert,update,delete on tables to edusentia_runtime;
  alter default privileges in schema documents grant select,insert,update,delete on tables to edusentia_runtime;
  alter default privileges in schema ops grant select,insert,update,delete on tables to edusentia_runtime;
  alter default privileges in schema services grant usage,select on sequences to edusentia_runtime;
  alter default privileges in schema documents grant usage,select on sequences to edusentia_runtime;
  alter default privileges in schema ops grant usage,select on sequences to edusentia_runtime;
end if; end$$;

create or replace function app.install_tenant_policy(p_schema text,p_table text,p_force boolean default true)
returns void language plpgsql security definer set search_path=pg_catalog,app as $$
begin
  if p_schema not in ('app','academics','finance','storage','audit','services','documents','ops') then raise exception 'invalid_schema'; end if;
  if not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid and a.attname='tenant_id' where n.nspname=p_schema and c.relname=p_table and c.relkind='r') then raise exception 'tenant_id_missing'; end if;
  execute format('alter table %I.%I enable row level security',p_schema,p_table);
  if p_force then execute format('alter table %I.%I force row level security',p_schema,p_table); end if;
  if not exists(select 1 from pg_policies where schemaname=p_schema and tablename=p_table and policyname='tenant_isolation') then
    execute format('create policy tenant_isolation on %I.%I using (tenant_id=app.current_tenant_id()) with check (tenant_id=app.current_tenant_id())',p_schema,p_table);
  end if;
end$$;
revoke all on function app.install_tenant_policy(text,text,boolean) from public;

create table if not exists academics.faculties(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,code text not null,name text not null,active boolean not null default true,archived_at timestamptz,unique(tenant_id,code));
create table if not exists academics.departments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,faculty_id uuid references academics.faculties(id),code text not null,name text not null,active boolean not null default true,archived_at timestamptz,unique(tenant_id,code));
create table if not exists academics.programmes(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,department_id uuid references academics.departments(id),code text not null,name text not null,programme_type text not null default 'general',duration_terms integer,active boolean not null default true,archived_at timestamptz,unique(tenant_id,code));
create table if not exists academics.levels(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,code text not null,name text not null,level_order integer not null default 0,active boolean not null default true,unique(tenant_id,code));
create table if not exists academics.academic_period_controls(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,academic_year_id uuid references academics.academic_years(id),term_id uuid references academics.terms(id),phase text not null default 'open',score_entry_open boolean not null default true,report_entry_open boolean not null default true,locked_at timestamptz,locked_by uuid references authn.users(id),unique(tenant_id,academic_year_id,term_id));
create table if not exists academics.teachers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,staff_id uuid references app.staff(id),user_id uuid references authn.users(id),teacher_no text,display_name text not null,active boolean not null default true,archived_at timestamptz,unique(tenant_id,teacher_no));
create table if not exists academics.headteachers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,staff_id uuid references app.staff(id),user_id uuid references authn.users(id),display_name text not null,signature_object_key text,active boolean not null default true,archived_at timestamptz);
create table if not exists academics.class_timetable_entries(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,class_id uuid not null references academics.classes(id),subject_id uuid references academics.subjects(id),teacher_id uuid references academics.teachers(id),weekday smallint not null check(weekday between 1 and 7),start_time time not null,end_time time not null,room text not null default '',active boolean not null default true,check(start_time<end_time));
create table if not exists academics.teacher_class_assignments(tenant_id uuid not null references app.tenants(id) on delete cascade,teacher_id uuid not null references academics.teachers(id) on delete cascade,class_id uuid not null references academics.classes(id) on delete cascade,is_class_teacher boolean not null default false,primary key(teacher_id,class_id));
create table if not exists academics.teacher_subject_assignments(tenant_id uuid not null references app.tenants(id) on delete cascade,teacher_id uuid not null references academics.teachers(id) on delete cascade,class_id uuid not null references academics.classes(id) on delete cascade,subject_id uuid not null references academics.subjects(id) on delete cascade,primary key(teacher_id,class_id,subject_id));
create table if not exists academics.shs_programme_subjects(tenant_id uuid not null references app.tenants(id) on delete cascade,programme_id uuid not null references academics.programmes(id) on delete cascade,subject_id uuid not null references academics.subjects(id),core boolean not null default false,primary key(programme_id,subject_id));
create table if not exists academics.tertiary_courses(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,department_id uuid references academics.departments(id),code text not null,title text not null,credit_hours numeric(4,1) not null default 0,active boolean not null default true,unique(tenant_id,code));
create table if not exists academics.tertiary_programme_courses(tenant_id uuid not null references app.tenants(id) on delete cascade,programme_id uuid not null references academics.programmes(id) on delete cascade,course_id uuid not null references academics.tertiary_courses(id) on delete cascade,level_id uuid references academics.levels(id),term_sequence smallint,required boolean not null default true,primary key(programme_id,course_id));
create table if not exists academics.tertiary_course_prerequisites(tenant_id uuid not null references app.tenants(id) on delete cascade,course_id uuid not null references academics.tertiary_courses(id) on delete cascade,prerequisite_course_id uuid not null references academics.tertiary_courses(id),primary key(course_id,prerequisite_course_id));
create table if not exists academics.tertiary_course_offerings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,course_id uuid not null references academics.tertiary_courses(id),academic_year_id uuid not null references academics.academic_years(id),term_id uuid not null references academics.terms(id),teacher_id uuid references academics.teachers(id),capacity integer,status text not null default 'open',unique(tenant_id,course_id,term_id));
create table if not exists academics.tertiary_course_registrations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,offering_id uuid not null references academics.tertiary_course_offerings(id),student_id uuid not null references app.students(id),status text not null default 'registered',registered_at timestamptz not null default now(),unique(offering_id,student_id));
create table if not exists academics.tertiary_course_results(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,registration_id uuid not null references academics.tertiary_course_registrations(id),score numeric(6,2),grade text,grade_points numeric(5,2),status text not null default 'draft',recorded_by uuid references authn.users(id),updated_at timestamptz not null default now(),unique(registration_id));
create table if not exists academics.tertiary_grading_scale(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,min_score numeric(6,2) not null,max_score numeric(6,2) not null,grade text not null,grade_points numeric(5,2) not null,classification text,check(min_score<=max_score));
create table if not exists academics.tertiary_degree_classifications(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,min_cgpa numeric(5,2) not null,max_cgpa numeric(5,2) not null,label text not null,check(min_cgpa<=max_cgpa));
create table if not exists academics.tertiary_programme_requirements(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,programme_id uuid not null references academics.programmes(id),min_credits numeric(7,2) not null default 0,min_cgpa numeric(5,2),requirements jsonb not null default '{}'::jsonb,unique(tenant_id,programme_id));
create table if not exists academics.student_programme_enrollments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,student_id uuid not null references app.students(id),programme_id uuid not null references academics.programmes(id),level_id uuid references academics.levels(id),academic_year_id uuid references academics.academic_years(id),status text not null default 'active',started_at date,completed_at date,unique(tenant_id,student_id,programme_id,status));
create table if not exists academics.emergency_delegations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,delegator_id uuid not null references authn.users(id),delegate_id uuid not null references authn.users(id),scope jsonb not null default '{}'::jsonb,reason text not null,starts_at timestamptz not null,ends_at timestamptz not null,status text not null default 'pending',acknowledged_at timestamptz,revoked_at timestamptz,check(starts_at<ends_at));
create table if not exists academics.emergency_delegation_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,delegation_id uuid not null references academics.emergency_delegations(id) on delete cascade,event_type text not null,actor_id uuid references authn.users(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

do $$declare t text; begin foreach t in array array['faculties','departments','programmes','levels','academic_period_controls','class_timetable_entries','teachers','headteachers','teacher_class_assignments','teacher_subject_assignments','shs_programme_subjects','tertiary_courses','tertiary_programme_courses','tertiary_course_prerequisites','tertiary_course_offerings','tertiary_course_registrations','tertiary_course_results','tertiary_grading_scale','tertiary_degree_classifications','tertiary_programme_requirements','student_programme_enrollments','emergency_delegations','emergency_delegation_events'] loop perform app.install_tenant_policy('academics',t,true); end loop; end$$;

do $$begin if exists(select 1 from pg_roles where rolname='edusentia_runtime') then grant select,insert,update,delete on all tables in schema services,documents,ops to edusentia_runtime; grant usage,select on all sequences in schema services,documents,ops to edusentia_runtime; end if; end$$;
insert into app.schema_migrations(version) values ('0009_academic_models') on conflict do nothing;
update app.release_identity set schema_version='0009' where edition='Edusentia Enterprise Neon Edition';
commit;
