begin;
create table if not exists documents.report_card_templates(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,name text not null,school_type text,template_object_key text,settings jsonb not null default '{}'::jsonb,active boolean not null default true,created_by uuid references authn.users(id),created_at timestamptz not null default now());
create table if not exists documents.report_revisions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,report_id uuid not null references academics.student_reports(id),revision_no integer not null,snapshot jsonb not null,created_by uuid references authn.users(id),created_at timestamptz not null default now(),unique(report_id,revision_no));
create table if not exists documents.report_publications(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,report_id uuid not null references academics.student_reports(id),revision_id uuid references documents.report_revisions(id),pdf_object_key text,verification_token text not null unique,published_by uuid references authn.users(id),published_at timestamptz not null default now(),superseded_at timestamptz);
create table if not exists documents.report_correction_requests(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,report_id uuid not null references academics.student_reports(id),requested_by uuid references authn.users(id),reason text not null,status text not null default 'pending',reviewed_by uuid references authn.users(id),reviewed_at timestamptz,created_at timestamptz not null default now());
create table if not exists documents.report_correction_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,request_id uuid not null references documents.report_correction_requests(id) on delete cascade,event_type text not null,actor_id uuid references authn.users(id),note text not null default '',created_at timestamptz not null default now());
create table if not exists documents.certificate_templates(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,name text not null,certificate_type text not null,template_object_key text,settings jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists documents.certificate_batches(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,batch_no text not null,certificate_type text not null,status text not null default 'draft',created_by uuid references authn.users(id),submitted_at timestamptz,reviewed_by uuid references authn.users(id),reviewed_at timestamptz,unique(tenant_id,batch_no));
create table if not exists documents.certificate_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,certificate_id uuid references academics.certificates(id),batch_id uuid references documents.certificate_batches(id),event_type text not null,actor_id uuid references authn.users(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists documents.id_card_settings(tenant_id uuid primary key references app.tenants(id) on delete cascade,student_template jsonb not null default '{}'::jsonb,staff_template jsonb not null default '{}'::jsonb,updated_by uuid references authn.users(id),updated_at timestamptz not null default now());
create table if not exists documents.student_id_cards(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,student_id uuid not null references app.students(id),card_no text not null,verification_token text not null unique,photo_object_key text,status text not null default 'active',issued_at timestamptz not null default now(),expires_on date,replaced_by uuid references documents.student_id_cards(id),revoked_at timestamptz,unique(tenant_id,card_no));
create table if not exists documents.staff_id_cards(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,staff_id uuid not null references app.staff(id),card_no text not null,verification_token text not null unique,photo_object_key text,status text not null default 'active',issued_at timestamptz not null default now(),expires_on date,replaced_by uuid references documents.staff_id_cards(id),revoked_at timestamptz,unique(tenant_id,card_no));
create table if not exists documents.id_card_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,card_kind text not null,card_id uuid not null,event_type text not null,actor_id uuid references authn.users(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists documents.prospectuses(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,title text not null,academic_year_id uuid references academics.academic_years(id),status text not null default 'draft',published_at timestamptz,created_by uuid references authn.users(id),created_at timestamptz not null default now());
create table if not exists documents.prospectus_sections(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,prospectus_id uuid not null references documents.prospectuses(id) on delete cascade,title text not null,sequence integer not null default 1,content text not null default '');
create table if not exists documents.prospectus_items(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,section_id uuid not null references documents.prospectus_sections(id) on delete cascade,label text not null,description text,quantity text,required boolean not null default true,sequence integer not null default 1);
create table if not exists documents.prospectus_revisions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,prospectus_id uuid not null references documents.prospectuses(id),revision_no integer not null,snapshot jsonb not null,created_by uuid references authn.users(id),created_at timestamptz not null default now(),unique(prospectus_id,revision_no));

do $$declare t text; begin foreach t in array array['report_card_templates','report_revisions','report_publications','report_correction_requests','report_correction_events','certificate_templates','certificate_batches','certificate_events','id_card_settings','student_id_cards','staff_id_cards','id_card_events','prospectuses','prospectus_sections','prospectus_items','prospectus_revisions'] loop perform app.install_tenant_policy('documents',t,true); end loop; end$$;

do $$begin if exists(select 1 from pg_roles where rolname='edusentia_runtime') then grant select,insert,update,delete on all tables in schema documents to edusentia_runtime; grant usage,select on all sequences in schema documents to edusentia_runtime; end if; end$$;
insert into app.schema_migrations(version) values ('0012_documents_and_identity') on conflict do nothing;
update app.release_identity set schema_version='0012' where edition='Edusentia Enterprise Neon Edition';
commit;
