begin;
create schema if not exists platform;
create table if not exists ops.client_error_events(id bigint generated always as identity primary key,tenant_id uuid not null references app.tenants(id) on delete cascade,user_id uuid references authn.users(id),error_code text,message text,route text,client_version text,metadata jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());
create table if not exists ops.data_retention_policies(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,data_category text not null,retention_days integer not null check(retention_days>0),action text not null default 'archive',active boolean not null default true,updated_by uuid references authn.users(id),updated_at timestamptz not null default now(),unique(tenant_id,data_category));
create table if not exists ops.privacy_requests(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,request_type text not null,subject_user_id uuid references authn.users(id),requester_name text,requester_email text,status text not null default 'open',details text,opened_at timestamptz not null default now(),due_at timestamptz,closed_at timestamptz,handled_by uuid references authn.users(id));
create table if not exists ops.security_verification_runs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,verification_type text not null,status text not null default 'running',results jsonb not null default '{}'::jsonb,started_by uuid references authn.users(id),started_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists ops.backup_storage_objects(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,backup_export_id uuid references app.backup_exports(id),object_key text not null,checksum_sha256 text,size_bytes bigint,status text not null default 'active',created_at timestamptz not null default now(),unique(tenant_id,object_key));
create table if not exists ops.restore_jobs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,backup_export_id uuid references app.backup_exports(id),status text not null default 'requested',requested_by uuid references authn.users(id),requested_at timestamptz not null default now(),started_at timestamptz,completed_at timestamptz,error_code text);
create table if not exists ops.restore_stage_tables(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,restore_job_id uuid not null references ops.restore_jobs(id) on delete cascade,table_name text not null,row_count bigint not null default 0,checksum text,status text not null default 'pending',unique(restore_job_id,table_name));
create table if not exists ops.import_batches(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,import_type text not null,source_object_key text,file_name text,status text not null default 'uploaded',row_count integer not null default 0,success_count integer not null default 0,error_count integer not null default 0,created_by uuid references authn.users(id),created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists ops.import_errors(id bigint generated always as identity primary key,tenant_id uuid not null references app.tenants(id) on delete cascade,batch_id uuid not null references ops.import_batches(id) on delete cascade,row_number integer,column_name text,error_code text,message text not null,raw_value text);
create table if not exists ops.system_release_state(tenant_id uuid primary key references app.tenants(id) on delete cascade,release_version text not null,schema_version text not null,frontend_version text not null,worker_version text not null,verified_at timestamptz,verification_status text not null default 'pending');
create table if not exists ops.system_maintenance_log(id bigint generated always as identity primary key,tenant_id uuid not null references app.tenants(id) on delete cascade,operation text not null,status text not null,actor_id uuid references authn.users(id),details jsonb not null default '{}'::jsonb,started_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists ops.audit_archives(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,period_start timestamptz not null,period_end timestamptz not null,object_key text not null,checksum_sha256 text,row_count bigint not null default 0,created_at timestamptz not null default now());
create table if not exists ops.student_lifecycle_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,student_id uuid not null references app.students(id),event_type text not null,from_status text,to_status text,academic_year_id uuid references academics.academic_years(id),class_id uuid references academics.classes(id),actor_id uuid references authn.users(id),metadata jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());

create table if not exists platform.license_plans(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,active boolean not null default true,limits jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists platform.license_feature_catalog(code text primary key,name text not null,description text not null default '',default_enabled boolean not null default false);
create table if not exists app.tenant_licenses(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete cascade,plan_id uuid references platform.license_plans(id),status text not null default 'active',starts_at timestamptz not null default now(),expires_at timestamptz,feature_overrides jsonb not null default '{}'::jsonb,limits_override jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),unique(tenant_id));
create table if not exists app.license_events(id bigint generated always as identity primary key,tenant_id uuid not null references app.tenants(id) on delete cascade,event_type text not null,actor_id uuid references authn.users(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

do $$declare t text; begin foreach t in array array['client_error_events','data_retention_policies','privacy_requests','security_verification_runs','backup_storage_objects','restore_jobs','restore_stage_tables','import_batches','import_errors','system_release_state','system_maintenance_log','audit_archives','student_lifecycle_events'] loop perform app.install_tenant_policy('ops',t,true); end loop; end$$;
select app.install_tenant_policy('app','tenant_licenses',true);
select app.install_tenant_policy('app','license_events',true);

do $$begin if exists(select 1 from pg_roles where rolname='edusentia_runtime') then grant select,insert,update,delete on all tables in schema ops to edusentia_runtime; grant usage,select on all sequences in schema ops to edusentia_runtime; grant usage on schema platform to edusentia_runtime; grant select on platform.license_plans,platform.license_feature_catalog to edusentia_runtime; end if; end$$;
insert into app.schema_migrations(version) values ('0013_operations_compliance') on conflict do nothing;
update app.release_identity set schema_version='0013' where edition='Edusentia Enterprise Neon Edition';
commit;
